version: "3.7"

services:
  frontend:
    build: ./frontend/etc
    working_dir: /app
    command: npm run serve
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
  backend:
    build: ./backend/etc
    working_dir: /app
    command: npm run serve
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000